locals {
  control_plane_permissions = [
    # Networking: firewall rules scoped to the cluster's VMs in the customer's registered
    # network (docs/adr/0013). No network, subnet, router or NAT is created or deleted.
    "compute.networks.updatePolicy",
    "compute.networks.use",
    "compute.subnetworks.use",
    "compute.firewalls.create",
    "compute.firewalls.delete",
    "compute.firewalls.get",
    "compute.firewalls.update",
    # Network lookup (read-only); moves to the read-only monitor role in P4.
    "compute.networks.get",
    "compute.subnetworks.get",
    "compute.routers.list",
    # Compute and storage
    "compute.instances.create",
    "compute.instances.delete",
    "compute.instances.get",
    "compute.instances.list",
    "compute.instances.setMetadata",
    "compute.instances.setServiceAccount",
    "compute.instances.setTags",
    "compute.instances.setLabels",
    "compute.instances.attachDisk",
    "compute.instances.detachDisk",
    "compute.instances.start",
    "compute.instances.stop",
    "compute.instances.getGuestAttributes",
    "compute.disks.create",
    "compute.disks.delete",
    "compute.disks.get",
    "compute.disks.use",
    "compute.disks.setLabels",
    "compute.disks.resize",
    # Internal load balancer of the dedicated layout (docs/adr/0016).
    "compute.addresses.create",
    "compute.addresses.createInternal",
    "compute.addresses.delete",
    "compute.addresses.deleteInternal",
    "compute.addresses.get",
    "compute.addresses.setLabels",
    "compute.addresses.use",
    "compute.addresses.useInternal",
    "compute.instanceGroups.create",
    "compute.instanceGroups.delete",
    "compute.instanceGroups.get",
    "compute.instanceGroups.update",
    "compute.instanceGroups.use",
    "compute.instances.use",
    "compute.regionHealthChecks.create",
    "compute.regionHealthChecks.delete",
    "compute.regionHealthChecks.get",
    "compute.regionHealthChecks.update",
    "compute.regionHealthChecks.useReadOnly",
    "compute.regionBackendServices.create",
    "compute.regionBackendServices.delete",
    "compute.regionBackendServices.get",
    "compute.regionBackendServices.update",
    "compute.regionBackendServices.use",
    "compute.forwardingRules.create",
    "compute.forwardingRules.delete",
    "compute.forwardingRules.get",
    "compute.forwardingRules.setLabels",
    "compute.forwardingRules.update",
    "compute.forwardingRules.use",
    "compute.machineTypes.get",
    "compute.machineTypes.list",
    "compute.zones.get",
    "compute.zones.list",
    "compute.regions.get",
    "compute.regions.list",
    "compute.projects.get",
    "compute.zoneOperations.get",
    "compute.regionOperations.get",
    "compute.globalOperations.get",
    # Node service account
    "iam.serviceAccounts.create",
    "iam.serviceAccounts.delete",
    "iam.serviceAccounts.get",
    "iam.serviceAccounts.update",
    "iam.serviceAccounts.actAs",
    # Cluster secrets (TLS material, elastic password)
    "secretmanager.secrets.create",
    "secretmanager.secrets.delete",
    "secretmanager.secrets.get",
    "secretmanager.secrets.update",
    "secretmanager.secrets.getIamPolicy",
    "secretmanager.secrets.setIamPolicy",
    "secretmanager.versions.add",
    "secretmanager.versions.get",
    "secretmanager.versions.access",
    "secretmanager.versions.destroy",
    # Artifact bucket (agent binary)
    "storage.buckets.create",
    "storage.buckets.delete",
    "storage.buckets.get",
    "storage.buckets.update",
    "storage.buckets.getIamPolicy",
    "storage.buckets.setIamPolicy",
    "storage.objects.create",
    "storage.objects.delete",
    "storage.objects.get",
    "storage.objects.list",
    "resourcemanager.projects.get",
  ]
}
