"""Names of per-organization platform identities (docs/adr/0003, docs/adr/0014)."""

from __future__ import annotations

import hashlib
import secrets
import uuid


def organization_key(organization_id: uuid.UUID | str) -> str:
    """First 16 hex characters of SHA-256 of the organization's UUID; names its identities."""
    return hashlib.sha256(str(organization_id).encode()).hexdigest()[:16]


def new_external_id() -> str:
    """The AWS external ID of a new organization: generated by the platform, never chosen by the
    customer, so one organization cannot reuse another's."""
    return f"byoc-{secrets.token_hex(16)}"
